### ISSUE TITLE
Could not connect to "wss://api.openai.com/v1/realtime"

### ISSUE THREAD

**Issue by daishuge** [openai/openai-realtime-console#12] opened 2024-10-02 09:48 UTC
Uncaught runtime errors:
×
ERROR
Could not connect to "wss://api.openai.com/v1/realtime"
    at WebSocket.connectionErrorHandler (http://localhost:3000/static/js/bundle.js:57849:18)

**Comment by dqnamo** [comment] 2024-10-02 10:21
looks like not everybody has access yet https://github.com/openai/openai-realtime-console/issues/4

**Comment by daishuge** [comment] 2024-10-02 10:44
> looks like not everybody has access yet https://github.com/openai/openai-realtime-console/issues/4

Hi there!
When i login in on
 https://platform.openai.com/playground/realtime

It give me this:

Personal does not have access to the Realtime API.

I think this is the reason

**Comment by khorwood-openai** [comment] 2024-10-02 20:01
Closing as duplicate of https://github.com/openai/openai-realtime-console/issues/4

**Closed by khorwood-openai** 2024-10-02 20:01 UTC
